/**
 * Created by adrianotamburo on 16/11/2017.
 */
{
    "Antiques" : "Antiques",
    "Art" : "Art",
    "Baby" : "Baby",
    "Books" : "Books",
    "Business & Industrial" : "Business & Industrial",
    "Cameras & Photo" : "Cameras & Photo",
    "Cell Phones & Accessories" : "Cell Phones & Accessories",
    "Clothing, Shoes & Accessories" : "Clothing, Shoes & Accessories",
    "Coins & Paper Money" : "Coins & Paper Money",
    "Computers/Tablets & Networking" : "Computers/Tablets & Networking",
    "Consumer Electronics" : "Consumer Electronics",
    "Crafts" : "Crafts",
    "Dolls & Bears" : "Dolls & Bears",
    "DVDs & Movies" : "DVDs & Movies",
    "Entertainment Memorabilia" : "Entertainment Memorabilia",
    "Gift Cards & Coupons" : "Gift Cards & CouponsHealth & Beauty",
    "Health & BeautyHome & Garden" : "Home & Garden",
    "Jewelry & Watches", "Jewelry & Watches",
    "Music" : "Music",
    "Musical Instruments & Gear" : "Musical Instruments & Gear",
    "Pet Supplies" : "Pet Supplies",
    "Pottery & Glass" : "Pottery & Glass",
    "Real Estate" : "Real Estate",
    "Specialty Services" : "Specialty Services",
    "Sporting Goods" : "Sporting Goods",
    "Sports Mem, Cards & Fan Shop" , "Sports Mem, Cards & Fan Shop",
    "Stamps" : "Stamps",
    "Tickets & Experiences" : "Tickets & Experiences",
    "Toys & Hobbies" : "Toys & Hobbies",
    "Travel" : "Travel",
    "Video Games & Consoles" : "Video Games & Consoles",
    "Everything Else" : "Everything Else",
    "Cars and Other Vehicles" : "Cars and Other Vehicles",
    "Film and DVD" : "Film and DVD",
    "Art and Antiques" : "Art and Antiques"
}